// Code generated by go-swagger; DO NOT EDIT.

package answer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// CreatePreTestingOKCode is the HTTP code returned for type CreatePreTestingOK
const CreatePreTestingOKCode int = 200

/*CreatePreTestingOK Asked for PreTesting

swagger:response createPreTestingOK
*/
type CreatePreTestingOK struct {
}

// NewCreatePreTestingOK creates CreatePreTestingOK with default headers values
func NewCreatePreTestingOK() *CreatePreTestingOK {

	return &CreatePreTestingOK{}
}

// WriteResponse to the client
func (o *CreatePreTestingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreatePreTestingBadRequestCode is the HTTP code returned for type CreatePreTestingBadRequest
const CreatePreTestingBadRequestCode int = 400

/*CreatePreTestingBadRequest Incorrect Request, or invalida data

swagger:response createPreTestingBadRequest
*/
type CreatePreTestingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePreTestingBadRequest creates CreatePreTestingBadRequest with default headers values
func NewCreatePreTestingBadRequest() *CreatePreTestingBadRequest {

	return &CreatePreTestingBadRequest{}
}

// WithPayload adds the payload to the create pre testing bad request response
func (o *CreatePreTestingBadRequest) WithPayload(payload *models.Error) *CreatePreTestingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pre testing bad request response
func (o *CreatePreTestingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePreTestingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePreTestingForbiddenCode is the HTTP code returned for type CreatePreTestingForbidden
const CreatePreTestingForbiddenCode int = 403

/*CreatePreTestingForbidden Not authorized to this content

swagger:response createPreTestingForbidden
*/
type CreatePreTestingForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePreTestingForbidden creates CreatePreTestingForbidden with default headers values
func NewCreatePreTestingForbidden() *CreatePreTestingForbidden {

	return &CreatePreTestingForbidden{}
}

// WithPayload adds the payload to the create pre testing forbidden response
func (o *CreatePreTestingForbidden) WithPayload(payload *models.Error) *CreatePreTestingForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pre testing forbidden response
func (o *CreatePreTestingForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePreTestingForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePreTestingGoneCode is the HTTP code returned for type CreatePreTestingGone
const CreatePreTestingGoneCode int = 410

/*CreatePreTestingGone That resource does not exist

swagger:response createPreTestingGone
*/
type CreatePreTestingGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreatePreTestingGone creates CreatePreTestingGone with default headers values
func NewCreatePreTestingGone() *CreatePreTestingGone {

	return &CreatePreTestingGone{}
}

// WithPayload adds the payload to the create pre testing gone response
func (o *CreatePreTestingGone) WithPayload(payload *models.Error) *CreatePreTestingGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create pre testing gone response
func (o *CreatePreTestingGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePreTestingGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePreTestingInternalServerErrorCode is the HTTP code returned for type CreatePreTestingInternalServerError
const CreatePreTestingInternalServerErrorCode int = 500

/*CreatePreTestingInternalServerError Internal error

swagger:response createPreTestingInternalServerError
*/
type CreatePreTestingInternalServerError struct {
}

// NewCreatePreTestingInternalServerError creates CreatePreTestingInternalServerError with default headers values
func NewCreatePreTestingInternalServerError() *CreatePreTestingInternalServerError {

	return &CreatePreTestingInternalServerError{}
}

// WriteResponse to the client
func (o *CreatePreTestingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
