// Code generated by go-swagger; DO NOT EDIT.

package answer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// SetAnswerNotCorrectedHandlerFunc turns a function with the right signature into a set answer not corrected handler
type SetAnswerNotCorrectedHandlerFunc func(SetAnswerNotCorrectedParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn SetAnswerNotCorrectedHandlerFunc) Handle(params SetAnswerNotCorrectedParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// SetAnswerNotCorrectedHandler interface for that can handle valid set answer not corrected params
type SetAnswerNotCorrectedHandler interface {
	Handle(SetAnswerNotCorrectedParams, *models.User) middleware.Responder
}

// NewSetAnswerNotCorrected creates a new http.Handler for the set answer not corrected operation
func NewSetAnswerNotCorrected(ctx *middleware.Context, handler SetAnswerNotCorrectedHandler) *SetAnswerNotCorrected {
	return &SetAnswerNotCorrected{Context: ctx, Handler: handler}
}

/* SetAnswerNotCorrected swagger:route DELETE /answers/{answerid}/corrected answer setAnswerNotCorrected

Marks answer as not corrected. Only for TestAdmins

Marks answer as not corrected

*/
type SetAnswerNotCorrected struct {
	Context *middleware.Context
	Handler SetAnswerNotCorrectedHandler
}

func (o *SetAnswerNotCorrected) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSetAnswerNotCorrectedParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
