// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// AddTagToTestHandlerFunc turns a function with the right signature into a add tag to test handler
type AddTagToTestHandlerFunc func(AddTagToTestParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn AddTagToTestHandlerFunc) Handle(params AddTagToTestParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// AddTagToTestHandler interface for that can handle valid add tag to test params
type AddTagToTestHandler interface {
	Handle(AddTagToTestParams, *models.User) middleware.Responder
}

// NewAddTagToTest creates a new http.Handler for the add tag to test operation
func NewAddTagToTest(ctx *middleware.Context, handler AddTagToTestHandler) *AddTagToTest {
	return &AddTagToTest{Context: ctx, Handler: handler}
}

/* AddTagToTest swagger:route PUT /tests/{testid}/tags/{tag} test addTagToTest

Adds a tag to a test

Adds a tag to a test

*/
type AddTagToTest struct {
	Context *middleware.Context
	Handler AddTagToTestHandler
}

func (o *AddTagToTest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAddTagToTestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
