// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// GetAllEditTestsOKCode is the HTTP code returned for type GetAllEditTestsOK
const GetAllEditTestsOKCode int = 200

/*GetAllEditTestsOK tests found

swagger:response getAllEditTestsOK
*/
type GetAllEditTestsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Test `json:"body,omitempty"`
}

// NewGetAllEditTestsOK creates GetAllEditTestsOK with default headers values
func NewGetAllEditTestsOK() *GetAllEditTestsOK {

	return &GetAllEditTestsOK{}
}

// WithPayload adds the payload to the get all edit tests o k response
func (o *GetAllEditTestsOK) WithPayload(payload []*models.Test) *GetAllEditTestsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all edit tests o k response
func (o *GetAllEditTestsOK) SetPayload(payload []*models.Test) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllEditTestsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Test, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllEditTestsBadRequestCode is the HTTP code returned for type GetAllEditTestsBadRequest
const GetAllEditTestsBadRequestCode int = 400

/*GetAllEditTestsBadRequest Incorrect Request, or invalida data

swagger:response getAllEditTestsBadRequest
*/
type GetAllEditTestsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllEditTestsBadRequest creates GetAllEditTestsBadRequest with default headers values
func NewGetAllEditTestsBadRequest() *GetAllEditTestsBadRequest {

	return &GetAllEditTestsBadRequest{}
}

// WithPayload adds the payload to the get all edit tests bad request response
func (o *GetAllEditTestsBadRequest) WithPayload(payload *models.Error) *GetAllEditTestsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all edit tests bad request response
func (o *GetAllEditTestsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllEditTestsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllEditTestsForbiddenCode is the HTTP code returned for type GetAllEditTestsForbidden
const GetAllEditTestsForbiddenCode int = 403

/*GetAllEditTestsForbidden Not authorized to this content

swagger:response getAllEditTestsForbidden
*/
type GetAllEditTestsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllEditTestsForbidden creates GetAllEditTestsForbidden with default headers values
func NewGetAllEditTestsForbidden() *GetAllEditTestsForbidden {

	return &GetAllEditTestsForbidden{}
}

// WithPayload adds the payload to the get all edit tests forbidden response
func (o *GetAllEditTestsForbidden) WithPayload(payload *models.Error) *GetAllEditTestsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all edit tests forbidden response
func (o *GetAllEditTestsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllEditTestsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAllEditTestsInternalServerErrorCode is the HTTP code returned for type GetAllEditTestsInternalServerError
const GetAllEditTestsInternalServerErrorCode int = 500

/*GetAllEditTestsInternalServerError Internal error

swagger:response getAllEditTestsInternalServerError
*/
type GetAllEditTestsInternalServerError struct {
}

// NewGetAllEditTestsInternalServerError creates GetAllEditTestsInternalServerError with default headers values
func NewGetAllEditTestsInternalServerError() *GetAllEditTestsInternalServerError {

	return &GetAllEditTestsInternalServerError{}
}

// WriteResponse to the client
func (o *GetAllEditTestsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
