// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetTestsHandlerFunc turns a function with the right signature into a get tests handler
type GetTestsHandlerFunc func(GetTestsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTestsHandlerFunc) Handle(params GetTestsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetTestsHandler interface for that can handle valid get tests params
type GetTestsHandler interface {
	Handle(GetTestsParams, *models.User) middleware.Responder
}

// NewGetTests creates a new http.Handler for the get tests operation
func NewGetTests(ctx *middleware.Context, handler GetTestsHandler) *GetTests {
	return &GetTests{Context: ctx, Handler: handler}
}

/* GetTests swagger:route GET /tests test getTests

Returns all tests

Returns all tests

*/
type GetTests struct {
	Context *middleware.Context
	Handler GetTestsHandler
}

func (o *GetTests) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTestsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
