// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetQuestionFromTestHandlerFunc turns a function with the right signature into a get question from test handler
type GetQuestionFromTestHandlerFunc func(GetQuestionFromTestParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetQuestionFromTestHandlerFunc) Handle(params GetQuestionFromTestParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetQuestionFromTestHandler interface for that can handle valid get question from test params
type GetQuestionFromTestHandler interface {
	Handle(GetQuestionFromTestParams, *models.User) middleware.Responder
}

// NewGetQuestionFromTest creates a new http.Handler for the get question from test operation
func NewGetQuestionFromTest(ctx *middleware.Context, handler GetQuestionFromTestHandler) *GetQuestionFromTest {
	return &GetQuestionFromTest{Context: ctx, Handler: handler}
}

/* GetQuestionFromTest swagger:route GET /tests/{testid}/questions/{questionid} test getQuestionFromTest

Returns a question from a test

Returns a question from a test

*/
type GetQuestionFromTest struct {
	Context *middleware.Context
	Handler GetQuestionFromTestHandler
}

func (o *GetQuestionFromTest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetQuestionFromTestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
