// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetEditTestsFromTagParams creates a new GetEditTestsFromTagParams object
//
// There are no default values defined in the spec.
func NewGetEditTestsFromTagParams() GetEditTestsFromTagParams {

	return GetEditTestsFromTagParams{}
}

// GetEditTestsFromTagParams contains all the bound params for the get edit tests from tag operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetEditTestsFromTag
type GetEditTestsFromTagParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Tag to find its non published tests
	  Required: true
	  In: path
	*/
	Tag string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetEditTestsFromTagParams() beforehand.
func (o *GetEditTestsFromTagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTag, rhkTag, _ := route.Params.GetOK("tag")
	if err := o.bindTag(rTag, rhkTag, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTag binds and validates parameter Tag from path.
func (o *GetEditTestsFromTagParams) bindTag(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Tag = raw

	return nil
}
