// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// GetTagsOKCode is the HTTP code returned for type GetTagsOK
const GetTagsOKCode int = 200

/*GetTagsOK tags found

swagger:response getTagsOK
*/
type GetTagsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Tag `json:"body,omitempty"`
}

// NewGetTagsOK creates GetTagsOK with default headers values
func NewGetTagsOK() *GetTagsOK {

	return &GetTagsOK{}
}

// WithPayload adds the payload to the get tags o k response
func (o *GetTagsOK) WithPayload(payload []*models.Tag) *GetTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags o k response
func (o *GetTagsOK) SetPayload(payload []*models.Tag) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Tag, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTagsBadRequestCode is the HTTP code returned for type GetTagsBadRequest
const GetTagsBadRequestCode int = 400

/*GetTagsBadRequest Incorrect Request, or invalida data

swagger:response getTagsBadRequest
*/
type GetTagsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTagsBadRequest creates GetTagsBadRequest with default headers values
func NewGetTagsBadRequest() *GetTagsBadRequest {

	return &GetTagsBadRequest{}
}

// WithPayload adds the payload to the get tags bad request response
func (o *GetTagsBadRequest) WithPayload(payload *models.Error) *GetTagsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags bad request response
func (o *GetTagsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTagsForbiddenCode is the HTTP code returned for type GetTagsForbidden
const GetTagsForbiddenCode int = 403

/*GetTagsForbidden Not authorized to this content

swagger:response getTagsForbidden
*/
type GetTagsForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTagsForbidden creates GetTagsForbidden with default headers values
func NewGetTagsForbidden() *GetTagsForbidden {

	return &GetTagsForbidden{}
}

// WithPayload adds the payload to the get tags forbidden response
func (o *GetTagsForbidden) WithPayload(payload *models.Error) *GetTagsForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags forbidden response
func (o *GetTagsForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTagsInternalServerErrorCode is the HTTP code returned for type GetTagsInternalServerError
const GetTagsInternalServerErrorCode int = 500

/*GetTagsInternalServerError Internal error

swagger:response getTagsInternalServerError
*/
type GetTagsInternalServerError struct {
}

// NewGetTagsInternalServerError creates GetTagsInternalServerError with default headers values
func NewGetTagsInternalServerError() *GetTagsInternalServerError {

	return &GetTagsInternalServerError{}
}

// WriteResponse to the client
func (o *GetTagsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
