// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// DeletesPublishedTestOKCode is the HTTP code returned for type DeletesPublishedTestOK
const DeletesPublishedTestOKCode int = 200

/*DeletesPublishedTestOK PublishedTest deleted

swagger:response deletesPublishedTestOK
*/
type DeletesPublishedTestOK struct {
}

// NewDeletesPublishedTestOK creates DeletesPublishedTestOK with default headers values
func NewDeletesPublishedTestOK() *DeletesPublishedTestOK {

	return &DeletesPublishedTestOK{}
}

// WriteResponse to the client
func (o *DeletesPublishedTestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeletesPublishedTestBadRequestCode is the HTTP code returned for type DeletesPublishedTestBadRequest
const DeletesPublishedTestBadRequestCode int = 400

/*DeletesPublishedTestBadRequest Incorrect Request, or invalida data

swagger:response deletesPublishedTestBadRequest
*/
type DeletesPublishedTestBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletesPublishedTestBadRequest creates DeletesPublishedTestBadRequest with default headers values
func NewDeletesPublishedTestBadRequest() *DeletesPublishedTestBadRequest {

	return &DeletesPublishedTestBadRequest{}
}

// WithPayload adds the payload to the deletes published test bad request response
func (o *DeletesPublishedTestBadRequest) WithPayload(payload *models.Error) *DeletesPublishedTestBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deletes published test bad request response
func (o *DeletesPublishedTestBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletesPublishedTestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletesPublishedTestForbiddenCode is the HTTP code returned for type DeletesPublishedTestForbidden
const DeletesPublishedTestForbiddenCode int = 403

/*DeletesPublishedTestForbidden Not authorized to this content

swagger:response deletesPublishedTestForbidden
*/
type DeletesPublishedTestForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletesPublishedTestForbidden creates DeletesPublishedTestForbidden with default headers values
func NewDeletesPublishedTestForbidden() *DeletesPublishedTestForbidden {

	return &DeletesPublishedTestForbidden{}
}

// WithPayload adds the payload to the deletes published test forbidden response
func (o *DeletesPublishedTestForbidden) WithPayload(payload *models.Error) *DeletesPublishedTestForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deletes published test forbidden response
func (o *DeletesPublishedTestForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletesPublishedTestForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletesPublishedTestGoneCode is the HTTP code returned for type DeletesPublishedTestGone
const DeletesPublishedTestGoneCode int = 410

/*DeletesPublishedTestGone That user (password and name) does not exist

swagger:response deletesPublishedTestGone
*/
type DeletesPublishedTestGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletesPublishedTestGone creates DeletesPublishedTestGone with default headers values
func NewDeletesPublishedTestGone() *DeletesPublishedTestGone {

	return &DeletesPublishedTestGone{}
}

// WithPayload adds the payload to the deletes published test gone response
func (o *DeletesPublishedTestGone) WithPayload(payload *models.Error) *DeletesPublishedTestGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deletes published test gone response
func (o *DeletesPublishedTestGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletesPublishedTestGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeletesPublishedTestInternalServerErrorCode is the HTTP code returned for type DeletesPublishedTestInternalServerError
const DeletesPublishedTestInternalServerErrorCode int = 500

/*DeletesPublishedTestInternalServerError Internal error

swagger:response deletesPublishedTestInternalServerError
*/
type DeletesPublishedTestInternalServerError struct {
}

// NewDeletesPublishedTestInternalServerError creates DeletesPublishedTestInternalServerError with default headers values
func NewDeletesPublishedTestInternalServerError() *DeletesPublishedTestInternalServerError {

	return &DeletesPublishedTestInternalServerError{}
}

// WriteResponse to the client
func (o *DeletesPublishedTestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
