// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetTeamsFromPublishedTestHandlerFunc turns a function with the right signature into a get teams from published test handler
type GetTeamsFromPublishedTestHandlerFunc func(GetTeamsFromPublishedTestParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTeamsFromPublishedTestHandlerFunc) Handle(params GetTeamsFromPublishedTestParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetTeamsFromPublishedTestHandler interface for that can handle valid get teams from published test params
type GetTeamsFromPublishedTestHandler interface {
	Handle(GetTeamsFromPublishedTestParams, *models.User) middleware.Responder
}

// NewGetTeamsFromPublishedTest creates a new http.Handler for the get teams from published test operation
func NewGetTeamsFromPublishedTest(ctx *middleware.Context, handler GetTeamsFromPublishedTestHandler) *GetTeamsFromPublishedTest {
	return &GetTeamsFromPublishedTest{Context: ctx, Handler: handler}
}

/* GetTeamsFromPublishedTest swagger:route GET /publishedTests/{testid}/teams publishedTest getTeamsFromPublishedTest

Returns all teams from a publishedTest.

Returns all teams from a publishedTest.

*/
type GetTeamsFromPublishedTest struct {
	Context *middleware.Context
	Handler GetTeamsFromPublishedTestHandler
}

func (o *GetTeamsFromPublishedTest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetTeamsFromPublishedTestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
