// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetUncorrectedAnswersFromPublishedTestsParams creates a new GetUncorrectedAnswersFromPublishedTestsParams object
//
// There are no default values defined in the spec.
func NewGetUncorrectedAnswersFromPublishedTestsParams() GetUncorrectedAnswersFromPublishedTestsParams {

	return GetUncorrectedAnswersFromPublishedTestsParams{}
}

// GetUncorrectedAnswersFromPublishedTestsParams contains all the bound params for the get uncorrected answers from published tests operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetUncorrectedAnswersFromPublishedTests
type GetUncorrectedAnswersFromPublishedTestsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	OrderByAnswer *string
	/*Id of the publishedTest
	  Required: true
	  In: path
	*/
	Testid int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetUncorrectedAnswersFromPublishedTestsParams() beforehand.
func (o *GetUncorrectedAnswersFromPublishedTestsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qOrderByAnswer, qhkOrderByAnswer, _ := qs.GetOK("orderByAnswer")
	if err := o.bindOrderByAnswer(qOrderByAnswer, qhkOrderByAnswer, route.Formats); err != nil {
		res = append(res, err)
	}

	rTestid, rhkTestid, _ := route.Params.GetOK("testid")
	if err := o.bindTestid(rTestid, rhkTestid, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOrderByAnswer binds and validates parameter OrderByAnswer from query.
func (o *GetUncorrectedAnswersFromPublishedTestsParams) bindOrderByAnswer(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.OrderByAnswer = &raw

	if err := o.validateOrderByAnswer(formats); err != nil {
		return err
	}

	return nil
}

// validateOrderByAnswer carries on validations for parameter OrderByAnswer
func (o *GetUncorrectedAnswersFromPublishedTestsParams) validateOrderByAnswer(formats strfmt.Registry) error {

	if err := validate.EnumCase("orderByAnswer", "query", *o.OrderByAnswer, []interface{}{"newStartDate", "oldStartDate", "morePuntuacion", "lessPuntuacion", "moreDuracion", "lessDuracion"}, true); err != nil {
		return err
	}

	return nil
}

// bindTestid binds and validates parameter Testid from path.
func (o *GetUncorrectedAnswersFromPublishedTestsParams) bindTestid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("testid", "path", "int64", raw)
	}
	o.Testid = value

	return nil
}
