// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// GetTeamsFromPublishedTestOKCode is the HTTP code returned for type GetTeamsFromPublishedTestOK
const GetTeamsFromPublishedTestOKCode int = 200

/*GetTeamsFromPublishedTestOK teams found

swagger:response getTeamsFromPublishedTestOK
*/
type GetTeamsFromPublishedTestOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Team `json:"body,omitempty"`
}

// NewGetTeamsFromPublishedTestOK creates GetTeamsFromPublishedTestOK with default headers values
func NewGetTeamsFromPublishedTestOK() *GetTeamsFromPublishedTestOK {

	return &GetTeamsFromPublishedTestOK{}
}

// WithPayload adds the payload to the get teams from published test o k response
func (o *GetTeamsFromPublishedTestOK) WithPayload(payload []*models.Team) *GetTeamsFromPublishedTestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams from published test o k response
func (o *GetTeamsFromPublishedTestOK) SetPayload(payload []*models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsFromPublishedTestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Team, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTeamsFromPublishedTestBadRequestCode is the HTTP code returned for type GetTeamsFromPublishedTestBadRequest
const GetTeamsFromPublishedTestBadRequestCode int = 400

/*GetTeamsFromPublishedTestBadRequest Incorrect Request, or invalida data

swagger:response getTeamsFromPublishedTestBadRequest
*/
type GetTeamsFromPublishedTestBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamsFromPublishedTestBadRequest creates GetTeamsFromPublishedTestBadRequest with default headers values
func NewGetTeamsFromPublishedTestBadRequest() *GetTeamsFromPublishedTestBadRequest {

	return &GetTeamsFromPublishedTestBadRequest{}
}

// WithPayload adds the payload to the get teams from published test bad request response
func (o *GetTeamsFromPublishedTestBadRequest) WithPayload(payload *models.Error) *GetTeamsFromPublishedTestBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams from published test bad request response
func (o *GetTeamsFromPublishedTestBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsFromPublishedTestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTeamsFromPublishedTestForbiddenCode is the HTTP code returned for type GetTeamsFromPublishedTestForbidden
const GetTeamsFromPublishedTestForbiddenCode int = 403

/*GetTeamsFromPublishedTestForbidden Not authorized to this content

swagger:response getTeamsFromPublishedTestForbidden
*/
type GetTeamsFromPublishedTestForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamsFromPublishedTestForbidden creates GetTeamsFromPublishedTestForbidden with default headers values
func NewGetTeamsFromPublishedTestForbidden() *GetTeamsFromPublishedTestForbidden {

	return &GetTeamsFromPublishedTestForbidden{}
}

// WithPayload adds the payload to the get teams from published test forbidden response
func (o *GetTeamsFromPublishedTestForbidden) WithPayload(payload *models.Error) *GetTeamsFromPublishedTestForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams from published test forbidden response
func (o *GetTeamsFromPublishedTestForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsFromPublishedTestForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTeamsFromPublishedTestGoneCode is the HTTP code returned for type GetTeamsFromPublishedTestGone
const GetTeamsFromPublishedTestGoneCode int = 410

/*GetTeamsFromPublishedTestGone That user (password and name) does not exist

swagger:response getTeamsFromPublishedTestGone
*/
type GetTeamsFromPublishedTestGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamsFromPublishedTestGone creates GetTeamsFromPublishedTestGone with default headers values
func NewGetTeamsFromPublishedTestGone() *GetTeamsFromPublishedTestGone {

	return &GetTeamsFromPublishedTestGone{}
}

// WithPayload adds the payload to the get teams from published test gone response
func (o *GetTeamsFromPublishedTestGone) WithPayload(payload *models.Error) *GetTeamsFromPublishedTestGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams from published test gone response
func (o *GetTeamsFromPublishedTestGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsFromPublishedTestGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTeamsFromPublishedTestInternalServerErrorCode is the HTTP code returned for type GetTeamsFromPublishedTestInternalServerError
const GetTeamsFromPublishedTestInternalServerErrorCode int = 500

/*GetTeamsFromPublishedTestInternalServerError Internal error

swagger:response getTeamsFromPublishedTestInternalServerError
*/
type GetTeamsFromPublishedTestInternalServerError struct {
}

// NewGetTeamsFromPublishedTestInternalServerError creates GetTeamsFromPublishedTestInternalServerError with default headers values
func NewGetTeamsFromPublishedTestInternalServerError() *GetTeamsFromPublishedTestInternalServerError {

	return &GetTeamsFromPublishedTestInternalServerError{}
}

// WriteResponse to the client
func (o *GetTeamsFromPublishedTestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
