// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetCorrectedAnswersFromPublishedTestsHandlerFunc turns a function with the right signature into a get corrected answers from published tests handler
type GetCorrectedAnswersFromPublishedTestsHandlerFunc func(GetCorrectedAnswersFromPublishedTestsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCorrectedAnswersFromPublishedTestsHandlerFunc) Handle(params GetCorrectedAnswersFromPublishedTestsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetCorrectedAnswersFromPublishedTestsHandler interface for that can handle valid get corrected answers from published tests params
type GetCorrectedAnswersFromPublishedTestsHandler interface {
	Handle(GetCorrectedAnswersFromPublishedTestsParams, *models.User) middleware.Responder
}

// NewGetCorrectedAnswersFromPublishedTests creates a new http.Handler for the get corrected answers from published tests operation
func NewGetCorrectedAnswersFromPublishedTests(ctx *middleware.Context, handler GetCorrectedAnswersFromPublishedTestsHandler) *GetCorrectedAnswersFromPublishedTests {
	return &GetCorrectedAnswersFromPublishedTests{Context: ctx, Handler: handler}
}

/* GetCorrectedAnswersFromPublishedTests swagger:route GET /publishedTests/{testid}/correctedAnswers publishedTest getCorrectedAnswersFromPublishedTests

Returns all answers from a published test that are corrected

Returns all answers from a published test that are corrected

*/
type GetCorrectedAnswersFromPublishedTests struct {
	Context *middleware.Context
	Handler GetCorrectedAnswersFromPublishedTestsHandler
}

func (o *GetCorrectedAnswersFromPublishedTests) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCorrectedAnswersFromPublishedTestsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
