// Code generated by go-swagger; DO NOT EDIT.

package published_test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// RemoveUserToPublishedTestHandlerFunc turns a function with the right signature into a remove user to published test handler
type RemoveUserToPublishedTestHandlerFunc func(RemoveUserToPublishedTestParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveUserToPublishedTestHandlerFunc) Handle(params RemoveUserToPublishedTestParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// RemoveUserToPublishedTestHandler interface for that can handle valid remove user to published test params
type RemoveUserToPublishedTestHandler interface {
	Handle(RemoveUserToPublishedTestParams, *models.User) middleware.Responder
}

// NewRemoveUserToPublishedTest creates a new http.Handler for the remove user to published test operation
func NewRemoveUserToPublishedTest(ctx *middleware.Context, handler RemoveUserToPublishedTestHandler) *RemoveUserToPublishedTest {
	return &RemoveUserToPublishedTest{Context: ctx, Handler: handler}
}

/* RemoveUserToPublishedTest swagger:route DELETE /publishedTests/{testid}/users/{username} publishedTest removeUserToPublishedTest

Removes a user from a test

Removes a user to do a test

*/
type RemoveUserToPublishedTest struct {
	Context *middleware.Context
	Handler RemoveUserToPublishedTestHandler
}

func (o *RemoveUserToPublishedTest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRemoveUserToPublishedTestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
