// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// DeleteTeamOKCode is the HTTP code returned for type DeleteTeamOK
const DeleteTeamOKCode int = 200

/*DeleteTeamOK team found and deleted

swagger:response deleteTeamOK
*/
type DeleteTeamOK struct {
}

// NewDeleteTeamOK creates DeleteTeamOK with default headers values
func NewDeleteTeamOK() *DeleteTeamOK {

	return &DeleteTeamOK{}
}

// WriteResponse to the client
func (o *DeleteTeamOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteTeamBadRequestCode is the HTTP code returned for type DeleteTeamBadRequest
const DeleteTeamBadRequestCode int = 400

/*DeleteTeamBadRequest Incorrect Request, or invalida data

swagger:response deleteTeamBadRequest
*/
type DeleteTeamBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTeamBadRequest creates DeleteTeamBadRequest with default headers values
func NewDeleteTeamBadRequest() *DeleteTeamBadRequest {

	return &DeleteTeamBadRequest{}
}

// WithPayload adds the payload to the delete team bad request response
func (o *DeleteTeamBadRequest) WithPayload(payload *models.Error) *DeleteTeamBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete team bad request response
func (o *DeleteTeamBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTeamForbiddenCode is the HTTP code returned for type DeleteTeamForbidden
const DeleteTeamForbiddenCode int = 403

/*DeleteTeamForbidden Not authorized to this content

swagger:response deleteTeamForbidden
*/
type DeleteTeamForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTeamForbidden creates DeleteTeamForbidden with default headers values
func NewDeleteTeamForbidden() *DeleteTeamForbidden {

	return &DeleteTeamForbidden{}
}

// WithPayload adds the payload to the delete team forbidden response
func (o *DeleteTeamForbidden) WithPayload(payload *models.Error) *DeleteTeamForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete team forbidden response
func (o *DeleteTeamForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTeamGoneCode is the HTTP code returned for type DeleteTeamGone
const DeleteTeamGoneCode int = 410

/*DeleteTeamGone That user (password and name) does not exist

swagger:response deleteTeamGone
*/
type DeleteTeamGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTeamGone creates DeleteTeamGone with default headers values
func NewDeleteTeamGone() *DeleteTeamGone {

	return &DeleteTeamGone{}
}

// WithPayload adds the payload to the delete team gone response
func (o *DeleteTeamGone) WithPayload(payload *models.Error) *DeleteTeamGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete team gone response
func (o *DeleteTeamGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteTeamInternalServerErrorCode is the HTTP code returned for type DeleteTeamInternalServerError
const DeleteTeamInternalServerErrorCode int = 500

/*DeleteTeamInternalServerError Internal error

swagger:response deleteTeamInternalServerError
*/
type DeleteTeamInternalServerError struct {
}

// NewDeleteTeamInternalServerError creates DeleteTeamInternalServerError with default headers values
func NewDeleteTeamInternalServerError() *DeleteTeamInternalServerError {

	return &DeleteTeamInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteTeamInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
