// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetUserTeamRoleHandlerFunc turns a function with the right signature into a get user team role handler
type GetUserTeamRoleHandlerFunc func(GetUserTeamRoleParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUserTeamRoleHandlerFunc) Handle(params GetUserTeamRoleParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetUserTeamRoleHandler interface for that can handle valid get user team role params
type GetUserTeamRoleHandler interface {
	Handle(GetUserTeamRoleParams, *models.User) middleware.Responder
}

// NewGetUserTeamRole creates a new http.Handler for the get user team role operation
func NewGetUserTeamRole(ctx *middleware.Context, handler GetUserTeamRoleHandler) *GetUserTeamRole {
	return &GetUserTeamRole{Context: ctx, Handler: handler}
}

/* GetUserTeamRole swagger:route GET /users/{username}/teams/{teamname}/role team user getUserTeamRole

Returns the role of a user in a team

Returns the role of a user in a team

*/
type GetUserTeamRole struct {
	Context *middleware.Context
	Handler GetUserTeamRoleHandler
}

func (o *GetUserTeamRole) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUserTeamRoleParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
