export * from './answer.service';
import { AnswerService } from './answer.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './publishedTest.service';
import { PublishedTestService } from './publishedTest.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './tag.service';
import { TagService } from './tag.service';
export * from './team.service';
import { TeamService } from './team.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './tiporol.service';
import { TiporolService } from './tiporol.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AnswerService, AuthService, ConfigurationService, PublishedTestService, QuestionService, TagService, TeamService, TestService, TiporolService, UserService];
