/**
 * DevTest
 * DevTest
 *
 * OpenAPI spec version: 1.0.0
 * Contact: javigaton@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Test { 
    id?: number;
    title: string;
    description: string;
    maxMinutes: number;
    accesoPublico: boolean;
    editable: boolean;
    username: string;
    accesoPublicoNoPublicado: boolean;
    horaCreacion?: Date;
    originalTestID?: number;
    notaMaxima?: number;
    /**
     * only present in GetSolvableTestFromUser
     */
    cantidadRespuestasDelUsuario?: number;
    autoCorrect: boolean;
    visibilidad: Test.VisibilidadEnum;
    cantidadFavoritos?: number;
    tiempoEstricto: boolean;
    /**
     * Maximum of tries that a user has solving a test. If <1, there is no limit of tries.
     */
    maxIntentos: number;
}
export namespace Test {
    export type VisibilidadEnum = 'alEntregar' | 'alCorregir' | 'manual';
    export const VisibilidadEnum = {
        AlEntregar: 'alEntregar' as VisibilidadEnum,
        AlCorregir: 'alCorregir' as VisibilidadEnum,
        Manual: 'manual' as VisibilidadEnum
    };
}
