// Code generated by go-swagger; DO NOT EDIT.

package question

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteOptionParams creates a new DeleteOptionParams object
//
// There are no default values defined in the spec.
func NewDeleteOptionParams() DeleteOptionParams {

	return DeleteOptionParams{}
}

// DeleteOptionParams contains all the bound params for the delete option operation
// typically these are obtained from a http.Request
//
// swagger:parameters DeleteOption
type DeleteOptionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Index of the option to delete
	  Required: true
	  In: path
	*/
	Optionindex int64
	/*Id of the question to find its option
	  Required: true
	  In: path
	*/
	Questionid int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeleteOptionParams() beforehand.
func (o *DeleteOptionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rOptionindex, rhkOptionindex, _ := route.Params.GetOK("optionindex")
	if err := o.bindOptionindex(rOptionindex, rhkOptionindex, route.Formats); err != nil {
		res = append(res, err)
	}

	rQuestionid, rhkQuestionid, _ := route.Params.GetOK("questionid")
	if err := o.bindQuestionid(rQuestionid, rhkQuestionid, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOptionindex binds and validates parameter Optionindex from path.
func (o *DeleteOptionParams) bindOptionindex(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("optionindex", "path", "int64", raw)
	}
	o.Optionindex = value

	return nil
}

// bindQuestionid binds and validates parameter Questionid from path.
func (o *DeleteOptionParams) bindQuestionid(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("questionid", "path", "int64", raw)
	}
	o.Questionid = value

	return nil
}
