// Code generated by go-swagger; DO NOT EDIT.

package question

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetVisiblePruebasFromQuestionTestHandlerFunc turns a function with the right signature into a get visible pruebas from question test handler
type GetVisiblePruebasFromQuestionTestHandlerFunc func(GetVisiblePruebasFromQuestionTestParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVisiblePruebasFromQuestionTestHandlerFunc) Handle(params GetVisiblePruebasFromQuestionTestParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetVisiblePruebasFromQuestionTestHandler interface for that can handle valid get visible pruebas from question test params
type GetVisiblePruebasFromQuestionTestHandler interface {
	Handle(GetVisiblePruebasFromQuestionTestParams, *models.User) middleware.Responder
}

// NewGetVisiblePruebasFromQuestionTest creates a new http.Handler for the get visible pruebas from question test operation
func NewGetVisiblePruebasFromQuestionTest(ctx *middleware.Context, handler GetVisiblePruebasFromQuestionTestHandler) *GetVisiblePruebasFromQuestionTest {
	return &GetVisiblePruebasFromQuestionTest{Context: ctx, Handler: handler}
}

/* GetVisiblePruebasFromQuestionTest swagger:route GET /publishedTests/{testid}/questions/{questionid}/pruebas question getVisiblePruebasFromQuestionTest

Returns all pruebas visibles from a question.

Returns all pruebas visibles from a question.

*/
type GetVisiblePruebasFromQuestionTest struct {
	Context *middleware.Context
	Handler GetVisiblePruebasFromQuestionTestHandler
}

func (o *GetVisiblePruebasFromQuestionTest) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVisiblePruebasFromQuestionTestParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
