// Code generated by go-swagger; DO NOT EDIT.

package question

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetOptionsFromQuestionHandlerFunc turns a function with the right signature into a get options from question handler
type GetOptionsFromQuestionHandlerFunc func(GetOptionsFromQuestionParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOptionsFromQuestionHandlerFunc) Handle(params GetOptionsFromQuestionParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetOptionsFromQuestionHandler interface for that can handle valid get options from question params
type GetOptionsFromQuestionHandler interface {
	Handle(GetOptionsFromQuestionParams, *models.User) middleware.Responder
}

// NewGetOptionsFromQuestion creates a new http.Handler for the get options from question operation
func NewGetOptionsFromQuestion(ctx *middleware.Context, handler GetOptionsFromQuestionHandler) *GetOptionsFromQuestion {
	return &GetOptionsFromQuestion{Context: ctx, Handler: handler}
}

/* GetOptionsFromQuestion swagger:route GET /questions/{questionid}/options question getOptionsFromQuestion

Returns all options from a question.

Returns all options from a question.

*/
type GetOptionsFromQuestion struct {
	Context *middleware.Context
	Handler GetOptionsFromQuestionHandler
}

func (o *GetOptionsFromQuestion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetOptionsFromQuestionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
