// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// DeleteUserFromTeamOKCode is the HTTP code returned for type DeleteUserFromTeamOK
const DeleteUserFromTeamOKCode int = 200

/*DeleteUserFromTeamOK User deleted from team

swagger:response deleteUserFromTeamOK
*/
type DeleteUserFromTeamOK struct {
}

// NewDeleteUserFromTeamOK creates DeleteUserFromTeamOK with default headers values
func NewDeleteUserFromTeamOK() *DeleteUserFromTeamOK {

	return &DeleteUserFromTeamOK{}
}

// WriteResponse to the client
func (o *DeleteUserFromTeamOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUserFromTeamBadRequestCode is the HTTP code returned for type DeleteUserFromTeamBadRequest
const DeleteUserFromTeamBadRequestCode int = 400

/*DeleteUserFromTeamBadRequest Incorrect Request, or invalida data

swagger:response deleteUserFromTeamBadRequest
*/
type DeleteUserFromTeamBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserFromTeamBadRequest creates DeleteUserFromTeamBadRequest with default headers values
func NewDeleteUserFromTeamBadRequest() *DeleteUserFromTeamBadRequest {

	return &DeleteUserFromTeamBadRequest{}
}

// WithPayload adds the payload to the delete user from team bad request response
func (o *DeleteUserFromTeamBadRequest) WithPayload(payload *models.Error) *DeleteUserFromTeamBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user from team bad request response
func (o *DeleteUserFromTeamBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserFromTeamBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserFromTeamForbiddenCode is the HTTP code returned for type DeleteUserFromTeamForbidden
const DeleteUserFromTeamForbiddenCode int = 403

/*DeleteUserFromTeamForbidden Not authorized to this content

swagger:response deleteUserFromTeamForbidden
*/
type DeleteUserFromTeamForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserFromTeamForbidden creates DeleteUserFromTeamForbidden with default headers values
func NewDeleteUserFromTeamForbidden() *DeleteUserFromTeamForbidden {

	return &DeleteUserFromTeamForbidden{}
}

// WithPayload adds the payload to the delete user from team forbidden response
func (o *DeleteUserFromTeamForbidden) WithPayload(payload *models.Error) *DeleteUserFromTeamForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user from team forbidden response
func (o *DeleteUserFromTeamForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserFromTeamForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserFromTeamGoneCode is the HTTP code returned for type DeleteUserFromTeamGone
const DeleteUserFromTeamGoneCode int = 410

/*DeleteUserFromTeamGone That user (password and name) does not exist

swagger:response deleteUserFromTeamGone
*/
type DeleteUserFromTeamGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUserFromTeamGone creates DeleteUserFromTeamGone with default headers values
func NewDeleteUserFromTeamGone() *DeleteUserFromTeamGone {

	return &DeleteUserFromTeamGone{}
}

// WithPayload adds the payload to the delete user from team gone response
func (o *DeleteUserFromTeamGone) WithPayload(payload *models.Error) *DeleteUserFromTeamGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete user from team gone response
func (o *DeleteUserFromTeamGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUserFromTeamGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUserFromTeamInternalServerErrorCode is the HTTP code returned for type DeleteUserFromTeamInternalServerError
const DeleteUserFromTeamInternalServerErrorCode int = 500

/*DeleteUserFromTeamInternalServerError Internal error

swagger:response deleteUserFromTeamInternalServerError
*/
type DeleteUserFromTeamInternalServerError struct {
}

// NewDeleteUserFromTeamInternalServerError creates DeleteUserFromTeamInternalServerError with default headers values
func NewDeleteUserFromTeamInternalServerError() *DeleteUserFromTeamInternalServerError {

	return &DeleteUserFromTeamInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteUserFromTeamInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
