// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetSharedTestsFromUserHandlerFunc turns a function with the right signature into a get shared tests from user handler
type GetSharedTestsFromUserHandlerFunc func(GetSharedTestsFromUserParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSharedTestsFromUserHandlerFunc) Handle(params GetSharedTestsFromUserParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetSharedTestsFromUserHandler interface for that can handle valid get shared tests from user params
type GetSharedTestsFromUserHandler interface {
	Handle(GetSharedTestsFromUserParams, *models.User) middleware.Responder
}

// NewGetSharedTestsFromUser creates a new http.Handler for the get shared tests from user operation
func NewGetSharedTestsFromUser(ctx *middleware.Context, handler GetSharedTestsFromUserHandler) *GetSharedTestsFromUser {
	return &GetSharedTestsFromUser{Context: ctx, Handler: handler}
}

/* GetSharedTestsFromUser swagger:route GET /users/{username}/sharedTests user getSharedTestsFromUser

Returns all tests shared to a user (teacher).

Returns all tests shared to a user (teacher).

*/
type GetSharedTestsFromUser struct {
	Context *middleware.Context
	Handler GetSharedTestsFromUserHandler
}

func (o *GetSharedTestsFromUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSharedTestsFromUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
