// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetFavoriteEditQuestionsHandlerFunc turns a function with the right signature into a get favorite edit questions handler
type GetFavoriteEditQuestionsHandlerFunc func(GetFavoriteEditQuestionsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFavoriteEditQuestionsHandlerFunc) Handle(params GetFavoriteEditQuestionsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetFavoriteEditQuestionsHandler interface for that can handle valid get favorite edit questions params
type GetFavoriteEditQuestionsHandler interface {
	Handle(GetFavoriteEditQuestionsParams, *models.User) middleware.Responder
}

// NewGetFavoriteEditQuestions creates a new http.Handler for the get favorite edit questions operation
func NewGetFavoriteEditQuestions(ctx *middleware.Context, handler GetFavoriteEditQuestionsHandler) *GetFavoriteEditQuestions {
	return &GetFavoriteEditQuestions{Context: ctx, Handler: handler}
}

/* GetFavoriteEditQuestions swagger:route GET /users/{username}/favoriteEditQuestions user getFavoriteEditQuestions

Returns all non-published questions available for the user marked as its favorites

Returns all non-published questions available for the user marked as its favorites

*/
type GetFavoriteEditQuestions struct {
	Context *middleware.Context
	Handler GetFavoriteEditQuestionsHandler
}

func (o *GetFavoriteEditQuestions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFavoriteEditQuestionsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
