// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetPublishedTestFromUserHandlerFunc turns a function with the right signature into a get published test from user handler
type GetPublishedTestFromUserHandlerFunc func(GetPublishedTestFromUserParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPublishedTestFromUserHandlerFunc) Handle(params GetPublishedTestFromUserParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetPublishedTestFromUserHandler interface for that can handle valid get published test from user params
type GetPublishedTestFromUserHandler interface {
	Handle(GetPublishedTestFromUserParams, *models.User) middleware.Responder
}

// NewGetPublishedTestFromUser creates a new http.Handler for the get published test from user operation
func NewGetPublishedTestFromUser(ctx *middleware.Context, handler GetPublishedTestFromUserHandler) *GetPublishedTestFromUser {
	return &GetPublishedTestFromUser{Context: ctx, Handler: handler}
}

/* GetPublishedTestFromUser swagger:route GET /users/{username}/publishedTests/{testid} user getPublishedTestFromUser

Returns a publishedTest that the user can answer, including public ones and team ones.

Returns a publishedTest that the user can answer, including public ones and team ones.

*/
type GetPublishedTestFromUser struct {
	Context *middleware.Context
	Handler GetPublishedTestFromUserHandler
}

func (o *GetPublishedTestFromUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPublishedTestFromUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
