// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// GetUnfinishedAnswersFromUserAnsweredTestOKCode is the HTTP code returned for type GetUnfinishedAnswersFromUserAnsweredTestOK
const GetUnfinishedAnswersFromUserAnsweredTestOKCode int = 200

/*GetUnfinishedAnswersFromUserAnsweredTestOK answers found

swagger:response getUnfinishedAnswersFromUserAnsweredTestOK
*/
type GetUnfinishedAnswersFromUserAnsweredTestOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Answer `json:"body,omitempty"`
}

// NewGetUnfinishedAnswersFromUserAnsweredTestOK creates GetUnfinishedAnswersFromUserAnsweredTestOK with default headers values
func NewGetUnfinishedAnswersFromUserAnsweredTestOK() *GetUnfinishedAnswersFromUserAnsweredTestOK {

	return &GetUnfinishedAnswersFromUserAnsweredTestOK{}
}

// WithPayload adds the payload to the get unfinished answers from user answered test o k response
func (o *GetUnfinishedAnswersFromUserAnsweredTestOK) WithPayload(payload []*models.Answer) *GetUnfinishedAnswersFromUserAnsweredTestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get unfinished answers from user answered test o k response
func (o *GetUnfinishedAnswersFromUserAnsweredTestOK) SetPayload(payload []*models.Answer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUnfinishedAnswersFromUserAnsweredTestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Answer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetUnfinishedAnswersFromUserAnsweredTestBadRequestCode is the HTTP code returned for type GetUnfinishedAnswersFromUserAnsweredTestBadRequest
const GetUnfinishedAnswersFromUserAnsweredTestBadRequestCode int = 400

/*GetUnfinishedAnswersFromUserAnsweredTestBadRequest Incorrect Request, or invalida data

swagger:response getUnfinishedAnswersFromUserAnsweredTestBadRequest
*/
type GetUnfinishedAnswersFromUserAnsweredTestBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUnfinishedAnswersFromUserAnsweredTestBadRequest creates GetUnfinishedAnswersFromUserAnsweredTestBadRequest with default headers values
func NewGetUnfinishedAnswersFromUserAnsweredTestBadRequest() *GetUnfinishedAnswersFromUserAnsweredTestBadRequest {

	return &GetUnfinishedAnswersFromUserAnsweredTestBadRequest{}
}

// WithPayload adds the payload to the get unfinished answers from user answered test bad request response
func (o *GetUnfinishedAnswersFromUserAnsweredTestBadRequest) WithPayload(payload *models.Error) *GetUnfinishedAnswersFromUserAnsweredTestBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get unfinished answers from user answered test bad request response
func (o *GetUnfinishedAnswersFromUserAnsweredTestBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUnfinishedAnswersFromUserAnsweredTestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUnfinishedAnswersFromUserAnsweredTestForbiddenCode is the HTTP code returned for type GetUnfinishedAnswersFromUserAnsweredTestForbidden
const GetUnfinishedAnswersFromUserAnsweredTestForbiddenCode int = 403

/*GetUnfinishedAnswersFromUserAnsweredTestForbidden Not authorized to this content

swagger:response getUnfinishedAnswersFromUserAnsweredTestForbidden
*/
type GetUnfinishedAnswersFromUserAnsweredTestForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUnfinishedAnswersFromUserAnsweredTestForbidden creates GetUnfinishedAnswersFromUserAnsweredTestForbidden with default headers values
func NewGetUnfinishedAnswersFromUserAnsweredTestForbidden() *GetUnfinishedAnswersFromUserAnsweredTestForbidden {

	return &GetUnfinishedAnswersFromUserAnsweredTestForbidden{}
}

// WithPayload adds the payload to the get unfinished answers from user answered test forbidden response
func (o *GetUnfinishedAnswersFromUserAnsweredTestForbidden) WithPayload(payload *models.Error) *GetUnfinishedAnswersFromUserAnsweredTestForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get unfinished answers from user answered test forbidden response
func (o *GetUnfinishedAnswersFromUserAnsweredTestForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUnfinishedAnswersFromUserAnsweredTestForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUnfinishedAnswersFromUserAnsweredTestGoneCode is the HTTP code returned for type GetUnfinishedAnswersFromUserAnsweredTestGone
const GetUnfinishedAnswersFromUserAnsweredTestGoneCode int = 410

/*GetUnfinishedAnswersFromUserAnsweredTestGone That resource does not exist

swagger:response getUnfinishedAnswersFromUserAnsweredTestGone
*/
type GetUnfinishedAnswersFromUserAnsweredTestGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetUnfinishedAnswersFromUserAnsweredTestGone creates GetUnfinishedAnswersFromUserAnsweredTestGone with default headers values
func NewGetUnfinishedAnswersFromUserAnsweredTestGone() *GetUnfinishedAnswersFromUserAnsweredTestGone {

	return &GetUnfinishedAnswersFromUserAnsweredTestGone{}
}

// WithPayload adds the payload to the get unfinished answers from user answered test gone response
func (o *GetUnfinishedAnswersFromUserAnsweredTestGone) WithPayload(payload *models.Error) *GetUnfinishedAnswersFromUserAnsweredTestGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get unfinished answers from user answered test gone response
func (o *GetUnfinishedAnswersFromUserAnsweredTestGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUnfinishedAnswersFromUserAnsweredTestGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUnfinishedAnswersFromUserAnsweredTestInternalServerErrorCode is the HTTP code returned for type GetUnfinishedAnswersFromUserAnsweredTestInternalServerError
const GetUnfinishedAnswersFromUserAnsweredTestInternalServerErrorCode int = 500

/*GetUnfinishedAnswersFromUserAnsweredTestInternalServerError Internal error

swagger:response getUnfinishedAnswersFromUserAnsweredTestInternalServerError
*/
type GetUnfinishedAnswersFromUserAnsweredTestInternalServerError struct {
}

// NewGetUnfinishedAnswersFromUserAnsweredTestInternalServerError creates GetUnfinishedAnswersFromUserAnsweredTestInternalServerError with default headers values
func NewGetUnfinishedAnswersFromUserAnsweredTestInternalServerError() *GetUnfinishedAnswersFromUserAnsweredTestInternalServerError {

	return &GetUnfinishedAnswersFromUserAnsweredTestInternalServerError{}
}

// WriteResponse to the client
func (o *GetUnfinishedAnswersFromUserAnsweredTestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
