// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetAnsweredTestFromUserHandlerFunc turns a function with the right signature into a get answered test from user handler
type GetAnsweredTestFromUserHandlerFunc func(GetAnsweredTestFromUserParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAnsweredTestFromUserHandlerFunc) Handle(params GetAnsweredTestFromUserParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetAnsweredTestFromUserHandler interface for that can handle valid get answered test from user params
type GetAnsweredTestFromUserHandler interface {
	Handle(GetAnsweredTestFromUserParams, *models.User) middleware.Responder
}

// NewGetAnsweredTestFromUser creates a new http.Handler for the get answered test from user operation
func NewGetAnsweredTestFromUser(ctx *middleware.Context, handler GetAnsweredTestFromUserHandler) *GetAnsweredTestFromUser {
	return &GetAnsweredTestFromUser{Context: ctx, Handler: handler}
}

/* GetAnsweredTestFromUser swagger:route GET /users/{username}/answeredTests/{testid} user getAnsweredTestFromUser

Returns a publishedTest that the user has answered

Returns a publishedTest that the user has answered

*/
type GetAnsweredTestFromUser struct {
	Context *middleware.Context
	Handler GetAnsweredTestFromUserHandler
}

func (o *GetAnsweredTestFromUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAnsweredTestFromUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
