// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetFavoriteEditTestsHandlerFunc turns a function with the right signature into a get favorite edit tests handler
type GetFavoriteEditTestsHandlerFunc func(GetFavoriteEditTestsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFavoriteEditTestsHandlerFunc) Handle(params GetFavoriteEditTestsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetFavoriteEditTestsHandler interface for that can handle valid get favorite edit tests params
type GetFavoriteEditTestsHandler interface {
	Handle(GetFavoriteEditTestsParams, *models.User) middleware.Responder
}

// NewGetFavoriteEditTests creates a new http.Handler for the get favorite edit tests operation
func NewGetFavoriteEditTests(ctx *middleware.Context, handler GetFavoriteEditTestsHandler) *GetFavoriteEditTests {
	return &GetFavoriteEditTests{Context: ctx, Handler: handler}
}

/* GetFavoriteEditTests swagger:route GET /users/{username}/favoriteEditTests user getFavoriteEditTests

Returns all non-published tests available for the user marked as its favorites

Returns all non-published tests available for the user marked as its favorites

*/
type GetFavoriteEditTests struct {
	Context *middleware.Context
	Handler GetFavoriteEditTestsHandler
}

func (o *GetFavoriteEditTests) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFavoriteEditTestsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
