// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// GetCorrectedAnswersFromUserOKCode is the HTTP code returned for type GetCorrectedAnswersFromUserOK
const GetCorrectedAnswersFromUserOKCode int = 200

/*GetCorrectedAnswersFromUserOK answers found

swagger:response getCorrectedAnswersFromUserOK
*/
type GetCorrectedAnswersFromUserOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Answer `json:"body,omitempty"`
}

// NewGetCorrectedAnswersFromUserOK creates GetCorrectedAnswersFromUserOK with default headers values
func NewGetCorrectedAnswersFromUserOK() *GetCorrectedAnswersFromUserOK {

	return &GetCorrectedAnswersFromUserOK{}
}

// WithPayload adds the payload to the get corrected answers from user o k response
func (o *GetCorrectedAnswersFromUserOK) WithPayload(payload []*models.Answer) *GetCorrectedAnswersFromUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrected answers from user o k response
func (o *GetCorrectedAnswersFromUserOK) SetPayload(payload []*models.Answer) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectedAnswersFromUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Answer, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetCorrectedAnswersFromUserBadRequestCode is the HTTP code returned for type GetCorrectedAnswersFromUserBadRequest
const GetCorrectedAnswersFromUserBadRequestCode int = 400

/*GetCorrectedAnswersFromUserBadRequest Incorrect Request, or invalida data

swagger:response getCorrectedAnswersFromUserBadRequest
*/
type GetCorrectedAnswersFromUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCorrectedAnswersFromUserBadRequest creates GetCorrectedAnswersFromUserBadRequest with default headers values
func NewGetCorrectedAnswersFromUserBadRequest() *GetCorrectedAnswersFromUserBadRequest {

	return &GetCorrectedAnswersFromUserBadRequest{}
}

// WithPayload adds the payload to the get corrected answers from user bad request response
func (o *GetCorrectedAnswersFromUserBadRequest) WithPayload(payload *models.Error) *GetCorrectedAnswersFromUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrected answers from user bad request response
func (o *GetCorrectedAnswersFromUserBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectedAnswersFromUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCorrectedAnswersFromUserForbiddenCode is the HTTP code returned for type GetCorrectedAnswersFromUserForbidden
const GetCorrectedAnswersFromUserForbiddenCode int = 403

/*GetCorrectedAnswersFromUserForbidden Not authorized to this content

swagger:response getCorrectedAnswersFromUserForbidden
*/
type GetCorrectedAnswersFromUserForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCorrectedAnswersFromUserForbidden creates GetCorrectedAnswersFromUserForbidden with default headers values
func NewGetCorrectedAnswersFromUserForbidden() *GetCorrectedAnswersFromUserForbidden {

	return &GetCorrectedAnswersFromUserForbidden{}
}

// WithPayload adds the payload to the get corrected answers from user forbidden response
func (o *GetCorrectedAnswersFromUserForbidden) WithPayload(payload *models.Error) *GetCorrectedAnswersFromUserForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrected answers from user forbidden response
func (o *GetCorrectedAnswersFromUserForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectedAnswersFromUserForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCorrectedAnswersFromUserGoneCode is the HTTP code returned for type GetCorrectedAnswersFromUserGone
const GetCorrectedAnswersFromUserGoneCode int = 410

/*GetCorrectedAnswersFromUserGone That resource does not exist

swagger:response getCorrectedAnswersFromUserGone
*/
type GetCorrectedAnswersFromUserGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCorrectedAnswersFromUserGone creates GetCorrectedAnswersFromUserGone with default headers values
func NewGetCorrectedAnswersFromUserGone() *GetCorrectedAnswersFromUserGone {

	return &GetCorrectedAnswersFromUserGone{}
}

// WithPayload adds the payload to the get corrected answers from user gone response
func (o *GetCorrectedAnswersFromUserGone) WithPayload(payload *models.Error) *GetCorrectedAnswersFromUserGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get corrected answers from user gone response
func (o *GetCorrectedAnswersFromUserGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCorrectedAnswersFromUserGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCorrectedAnswersFromUserInternalServerErrorCode is the HTTP code returned for type GetCorrectedAnswersFromUserInternalServerError
const GetCorrectedAnswersFromUserInternalServerErrorCode int = 500

/*GetCorrectedAnswersFromUserInternalServerError Internal error

swagger:response getCorrectedAnswersFromUserInternalServerError
*/
type GetCorrectedAnswersFromUserInternalServerError struct {
}

// NewGetCorrectedAnswersFromUserInternalServerError creates GetCorrectedAnswersFromUserInternalServerError with default headers values
func NewGetCorrectedAnswersFromUserInternalServerError() *GetCorrectedAnswersFromUserInternalServerError {

	return &GetCorrectedAnswersFromUserInternalServerError{}
}

// WriteResponse to the client
func (o *GetCorrectedAnswersFromUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
