// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// GetSharedQuestionsOfUserHandlerFunc turns a function with the right signature into a get shared questions of user handler
type GetSharedQuestionsOfUserHandlerFunc func(GetSharedQuestionsOfUserParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSharedQuestionsOfUserHandlerFunc) Handle(params GetSharedQuestionsOfUserParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// GetSharedQuestionsOfUserHandler interface for that can handle valid get shared questions of user params
type GetSharedQuestionsOfUserHandler interface {
	Handle(GetSharedQuestionsOfUserParams, *models.User) middleware.Responder
}

// NewGetSharedQuestionsOfUser creates a new http.Handler for the get shared questions of user operation
func NewGetSharedQuestionsOfUser(ctx *middleware.Context, handler GetSharedQuestionsOfUserHandler) *GetSharedQuestionsOfUser {
	return &GetSharedQuestionsOfUser{Context: ctx, Handler: handler}
}

/* GetSharedQuestionsOfUser swagger:route GET /users/{username}/sharedQuestions user getSharedQuestionsOfUser

Returns all questions is shared to the user

Returns all questions is shared to the user

*/
type GetSharedQuestionsOfUser struct {
	Context *middleware.Context
	Handler GetSharedQuestionsOfUserHandler
}

func (o *GetSharedQuestionsOfUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSharedQuestionsOfUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
