// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"uva-devtest/models"
)

// PostTestCreatedCode is the HTTP code returned for type PostTestCreated
const PostTestCreatedCode int = 201

/*PostTestCreated test created

swagger:response postTestCreated
*/
type PostTestCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Test `json:"body,omitempty"`
}

// NewPostTestCreated creates PostTestCreated with default headers values
func NewPostTestCreated() *PostTestCreated {

	return &PostTestCreated{}
}

// WithPayload adds the payload to the post test created response
func (o *PostTestCreated) WithPayload(payload *models.Test) *PostTestCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test created response
func (o *PostTestCreated) SetPayload(payload *models.Test) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestBadRequestCode is the HTTP code returned for type PostTestBadRequest
const PostTestBadRequestCode int = 400

/*PostTestBadRequest Incorrect Request, or invalida data

swagger:response postTestBadRequest
*/
type PostTestBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTestBadRequest creates PostTestBadRequest with default headers values
func NewPostTestBadRequest() *PostTestBadRequest {

	return &PostTestBadRequest{}
}

// WithPayload adds the payload to the post test bad request response
func (o *PostTestBadRequest) WithPayload(payload *models.Error) *PostTestBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test bad request response
func (o *PostTestBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestForbiddenCode is the HTTP code returned for type PostTestForbidden
const PostTestForbiddenCode int = 403

/*PostTestForbidden Not authorized to this content

swagger:response postTestForbidden
*/
type PostTestForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTestForbidden creates PostTestForbidden with default headers values
func NewPostTestForbidden() *PostTestForbidden {

	return &PostTestForbidden{}
}

// WithPayload adds the payload to the post test forbidden response
func (o *PostTestForbidden) WithPayload(payload *models.Error) *PostTestForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test forbidden response
func (o *PostTestForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestGoneCode is the HTTP code returned for type PostTestGone
const PostTestGoneCode int = 410

/*PostTestGone That user (password and name) does not exist

swagger:response postTestGone
*/
type PostTestGone struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTestGone creates PostTestGone with default headers values
func NewPostTestGone() *PostTestGone {

	return &PostTestGone{}
}

// WithPayload adds the payload to the post test gone response
func (o *PostTestGone) WithPayload(payload *models.Error) *PostTestGone {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post test gone response
func (o *PostTestGone) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTestGone) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(410)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostTestInternalServerErrorCode is the HTTP code returned for type PostTestInternalServerError
const PostTestInternalServerErrorCode int = 500

/*PostTestInternalServerError Internal error

swagger:response postTestInternalServerError
*/
type PostTestInternalServerError struct {
}

// NewPostTestInternalServerError creates PostTestInternalServerError with default headers values
func NewPostTestInternalServerError() *PostTestInternalServerError {

	return &PostTestInternalServerError{}
}

// WriteResponse to the client
func (o *PostTestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
