// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"uva-devtest/models"
)

// RemoveQuestionFavoriteHandlerFunc turns a function with the right signature into a remove question favorite handler
type RemoveQuestionFavoriteHandlerFunc func(RemoveQuestionFavoriteParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn RemoveQuestionFavoriteHandlerFunc) Handle(params RemoveQuestionFavoriteParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// RemoveQuestionFavoriteHandler interface for that can handle valid remove question favorite params
type RemoveQuestionFavoriteHandler interface {
	Handle(RemoveQuestionFavoriteParams, *models.User) middleware.Responder
}

// NewRemoveQuestionFavorite creates a new http.Handler for the remove question favorite operation
func NewRemoveQuestionFavorite(ctx *middleware.Context, handler RemoveQuestionFavoriteHandler) *RemoveQuestionFavorite {
	return &RemoveQuestionFavorite{Context: ctx, Handler: handler}
}

/* RemoveQuestionFavorite swagger:route DELETE /users/{username}/favoriteQuestions/{questionid} user removeQuestionFavorite

Marks question as non-favorite for the user

Marks question as non-favorite for the user

*/
type RemoveQuestionFavorite struct {
	Context *middleware.Context
	Handler RemoveQuestionFavoriteHandler
}

func (o *RemoveQuestionFavorite) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewRemoveQuestionFavoriteParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
